code d

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -51,14 +51,20 @@ jobs:
           aws s3 cp frontend/dist/ s3://lalitha-terraform-20240703-unique/ --recursive
 
       - name: Set Lambda environment variables
+        id: set_env
         run: |
-          echo "DATABASE=$(grep DATABASE backend/.env | cut -d '=' -f2-)" >> $GITHUB_ENV
+          DB=$(grep DATABASE backend/.env | cut -d '=' -f2-)
+          if [ -z "$DB" ]; then
+            echo "DATABASE variable is empty! Failing."
+            exit 1
+          fi
+          echo "DATABASE=$DB" >> $GITHUB_ENV
 
       - name: Upload backend to Lambda
         env:
           DATABASE: ${{ env.DATABASE }}
         run: |
           aws lambda update-function-code --function-name form-backend-api --zip-file fileb://backend/backend-lambda.zip
-          aws lambda update-function-configuration --function-name form-backend-api --environment "Variables={DATABASE=${{ env.DATABASE }}}"
+          aws lambda update-function-configuration --function-name form-backend-api --environment "Variables={DATABASE=\"$DATABASE\"}"
 
     
